### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ppaartha** [bushra-rafia/Bangla-Chatbot#1]
Is your trained dataset publicly available? If not can i get the dataset?

**Comment by bushra-rafia** [comment]
The project utilizes a primary dataset so the entire dataset is not available publicly. However, some portion of the data was sourced from public datasets. Below are the references to these public dataset sources that were combined in the final dataset.

- https://data.mendeley.com/datasets/s9pb3h2cjy/3/files/4d7436dc-03d4-497e-80bc-c5feb1eaf4cf
- https://huggingface.co/datasets/rasheduzzaman/Bangla_question_answer_pair_70K_dataset
- https://www.kaggle.com/datasets/abijitbarua/bangla-healthcare-chatbot-json-data

Thanks
